name: quantum-aco-dr
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
  - ibm-quantum
dependencies:
  # Python version
  - python=3.9
  
  # Core scientific computing
  - numpy>=1.21
  - scipy>=1.7
  - pandas>=1.3
  - scikit-learn>=1.0
  - matplotlib>=3.5
  - seaborn>=0.11
  
  # PyTorch with CUDA (adjust cudatoolkit version based on your GPU)
  - pytorch>=1.12
  - torchvision>=0.13
  - torchaudio>=0.12
  - cudatoolkit=11.3  # For CUDA 11.3, change based on your system
  
  # Quantum Computing
  - qiskit>=0.39
  - qiskit-ibmq-provider>=0.20
  - qiskit-aer>=0.11
  - qiskit-machine-learning>=0.5
  - pennylane>=0.25
  - pennylane-qiskit>=0.27
  
  # Machine Learning & Optimization
  - xgboost>=1.6
  - lightgbm>=3.3
  - optuna>=3.0
  - onnx>=1.12
  - onnxruntime>=1.12
  - onnxruntime-gpu>=1.12  # GPU acceleration for ONNX
  
  # Computer Vision & Image Processing
  - opencv>=4.6
  - pillow>=9.2
  - scikit-image>=0.19
  - albumentations>=1.3
  
  # Data Handling & Augmentation
  - imgaug>=0.4
  - tqdm>=4.64
  - joblib>=1.2
  
  # Weights & Biases for Experiment Tracking
  - wandb>=0.13
  
  # API & Web Framework
  - fastapi>=0.88
  - uvicorn>=0.20
  - python-multipart>=0.0
  - pydantic>=1.10
  
  # Dashboard & Visualization
  - streamlit>=1.19
  - plotly>=5.11
  - dash>=2.7
  - jupyter-dash>=0.4
  - ipywidgets>=8.0
  
  # Development Tools
  - jupyter>=1.0
  - jupyterlab>=3.4
  - ipython>=8.6
  - black>=22.12
  - flake8>=6.0
  - mypy>=1.0
  - pylint>=2.16
  
  # Utilities
  - requests>=2.28
  - beautifulsoup4>=4.11
  - lxml>=4.9
  - pyyaml>=6.0
  - python-dotenv>=0.21
  
  # System & Performance
  - psutil>=5.9
  - numba>=0.56
  - cupy-cuda11x>=11.0  # Optional: For GPU array operations
  
  # Medical Imaging Specific
  - pydicom>=2.3
  - nibabel>=5.0
  - SimpleITK>=2.2
  
  # Pip packages (for packages not available via conda)
  - pip
  - pip:
    # Quantum extras
    - qiskit-nature>=0.5
    - qiskit-optimization>=0.4
    - tensorflow-quantum>=0.7
    
    # ML Monitoring & Experiment Tracking
    - mlflow>=2.1
    - neptune-client>=1.0
    - comet-ml>=3.31
    
    # Advanced visualization
    - networkx>=3.0  # For ACO graph visualization
    - pyvis>=0.3  # Interactive network graphs
    
    # Dataset handling
    - kaggle>=1.5
    - datasets>=2.7  # Hugging Face datasets
    
    # Advanced optimizers for quantum
    - nevergrad>=0.8
    
    # Medical AI specific
    - monai>=1.0
    - torchio>=0.18
    
    # Quantum chemistry (for future molecular simulations)
    - pyscf>=2.1
    
    # ACO implementation library
    - aco-pants>=1.0.2
    
    # Async utilities
    - aiohttp>=3.8
    - asyncio>=3.4
    
    # CLI tools
    - typer>=0.7
    - rich>=13.0
    
    # Testing
    - pytest>=7.2
    - pytest-cov>=4.0
    - pytest-asyncio>=0.20
    
    # Documentation
    - mkdocs>=1.4
    - mkdocs-material>=9.0
